//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flashcards
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProgress
    {
        public long ProgressID { get; set; }
        public long fk_CardID { get; set; }
        public long fk_UserID { get; set; }
        public long Level { get; set; }
    
        public virtual TbCard TbCard { get; set; }
        public virtual TbLogin TbLogin { get; set; }
    }
}
